[package]
name = "otoa-input-kodama"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
ndarray.workspace = true
ort.workspace = true
otoa-input-onnx = { path = "../onnx" }
serde_json.workspace = true

[dev-dependencies]
sherpa-onnx.workspace = true
